runtime: python39
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  VARIABLE_NAME: 'value'

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "credentials/google-cloud-service-account.json"
